### ISSUE TITLE
Adding a new column to ahoy_events table

### ISSUE THREAD

**Issue by aniruddhbk** [ankane/ahoy#162]
How can I add a new column to the ahoy_events table, I want to avoid adding the attribute to the properties column cause I want to use the attribute directly in the query. I would prefer to do a query like 

where new_attribute=2 
rather than 
where properties LIKE '%\"new_attribute\":\"2"%'

Is this the right way of trying to extend ahoy or am I missing something?

**Comment by ankane** [comment]
If you use Postgres 9.4 or greater, queries on properties can be very fast if you use `jsonb` and index it, so that'd be my first choice.

Regardless, it's totally acceptable (and hopefully easy) to fit Ahoy to your needs.  You can define a custom `track_event` method that sets additional columns from keys in properties.

**Comment by aniruddhbk** [comment]
@ankane thanks
