### ISSUE TITLE
Missing visits - follow up

### ISSUE THREAD

**Issue by orczyk** [ankane/ahoy#240]
Hey, we opened this issue https://github.com/ankane/ahoy/issues/203 some time ago. We did ahoy update and we still have missing visits with additional issue of switching id - as described in linked issue.

I open this issue to make sure that issue is visible to anyone that may help. 

Any ideas?

Thanks a million.

**Comment by ctpelnar1988** [comment]
I am also having issues with this. Events track in DB with "visitor_id" included, but nothing is populating in Visit table.

**Comment by marcelokanzaki** [comment]
Visits get saved in development but in production, only Events are being recorded.

**Comment by ankane** [comment]
Who wants to dig in and get to the bottom of it?

**Comment by clouie87** [comment]
I am also experiencing this issue and I think it has to do with how Ahoy is determining a `new_visit?`. Ahoy uses the `ahoy_visit` param is in the cookie as an indicator that this visit has already been saved (without confirming that a corresponding visit exists in the database). 

Since ahoy.js will generate the cookie, cached content creates a cookie that doesn’t correspond to a visit in the database. Since there is a cookie, this visit is not treated as new, and never gets initialized, also it does not correspond to a visit in the database, so `current_visit` is nil. 

My current workaround is `ahoy.track_visit unless current_visit`

**Comment by ankane** [comment]
Hey @clouie87, not sure I follow the caching logic. Can you explain more?

**Comment by ayb** [comment]
This just started happening to me.  Have been using Ahoy for about 6 months.  Just noticed that events are actively being added but a new Visit record has not been created in about 2 days.

I'm using `ahoy.trackAll()` as well and have not made any recent javascript changes.

**Comment by ankane** [comment]
Cleaning up stale issues
