### ISSUE TITLE
Performance issue when querying properties on mysql

### ISSUE THREAD

**Issue by rocketblr** [ankane/ahoy#250]
Hi there,

We use the following call to display page view count to our users:
Ahoy::Event.where(name: "$view").where_properties(page: "value").count

As soon as the database grows this call is getting more and more time to execute.

Any suggestions?

Thanks,
Anatoly

**Comment by ankane** [comment]
Hey @rocketblr, my recommendation would be to use `track("Viewed <some-page>")` instead of `trackView()`. This allows you to query on name, which will be much more efficient (make sure you have an index on `name`).

If properties is a JSON column, you could also try [this approach](https://dev.mysql.com/doc/refman/5.7/en/create-table-secondary-indexes.html#json-column-indirect-index) to index it, but it's a bit more complicated.

**Comment by rocketblr** [comment]
@ankane Thanks!
