### ISSUE TITLE
Prevents ActionController::API from sending responses

### ISSUE THREAD

**Issue by ened** [ankane/ahoy#285]
My API controller methods try to render JSON responses using jbuilder:

```
  def companies    
    render template: 'api/v1/users/companies', 
        format: :json,
        locals: { companies: current_user.companies }
  end
```

However, all responses are now empty.

As a fix, I removed the call to `ActionController::Base.send :include` and `ActionController::API.send :include` in https://github.com/ankane/ahoy/blob/master/lib/ahoy.rb#L119 and include the modules now manually:

```
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  include Ahoy::Controller
```

```
class Api::ApiController < ActionController::API
  include Ahoy::Controller
```

I personally prefer this a lot, as it removes the magic and activates Ahoy explicitly.

Also see this PR for a similar discussion: https://github.com/rails/strong_parameters/pull/144

**Comment by coryschires** [comment]
### Background
I am having a similar problem. I've added Ahoy tracking to my application and it's working splendidly. Because `Ahoy::Controller` is automatically included in `ActionController::Base`, it's tracking visits for all users regardless which controller / action they have visited. For most users, I assume, this is the desired behavior. 

### Problem
In my case, however, I only need to track visits / events on a small part of my application (really just one controller). As a result, I'm currently tracking a lot of unnecessary visits. To be clear, everything works but ideally I'd like to avoid recording unnecessary visits (i.e. writes to my db, cluttered data, etc). 

### Solution
I'd like to suggest adding a configuration option which would allow you to opt out of the default track-everything-automatically behavior. For example, it would look something like:
    
    # add a new config option
    mattr_accessor :track_visits_automatically
    self.track_visits_automatically = true

    # include `Ahoy::Controller` conditionally
    ActiveSupport.on_load(:action_controller) do
      if Ahoy.track_visits_automatically
        ActionController::Base.send :include, Ahoy::Controller
        ActionController::API.send :include, Ahoy::Controller if defined?(ActionController::API)
      end
    end

This would solve not only my problem but also @ened problem. Furthermore, it would be non-breaking change should be a smooth release. 

@ankane Are you open to this idea? If yes, I'd be happy to make a PR. Please let me know.

**Comment by coryschires** [comment]
@ankane Just following up on this issue. Are you open to the idea of adding a new configuration option as described above?

**Comment by ankane** [comment]
Hey @coryschires, Ahoy does not track anything server-side automatically.

**Comment by coryschires** [comment]
Thanks for the quick response! 

After reading the source a bit more, I understand it does not track automatically on the server unless you set `Ahoy.track_visits_immediately = true`. So my concern is much less significant than I thought before. Thanks for clarifying. 

That said, Ahoy still mixes in a bunch of functionality (e.g. set cookies, etc). Ideally, I would like to include `Ahoy::Controller` myself – in the one place that I need it rather than globally in `ActionController`. So I think my suggestion still makes sense – at least for those users who: 

1. Would like to opt-out of the auto-include behavior. 
2. Set `Ahoy.track_visits_immediately = true` but are only using Ahoy in part of their app.

Finally, now that I understand the situation better, I think a better config option name would be something like `automatically_include_ahoy_controller`.

@ankane What do you think?

**Comment by ankane** [comment]
Hey @coryschires, thanks for the suggestions 👍  However, I don't see a strong reason for adding an option for this. Feel free to fork and comment out the "magic" if needed.
