### ISSUE TITLE
visit started_at is not equal to its first event's time

### ISSUE THREAD

**Issue by josh-m-sharpe** [ankane/ahoy#369]
In almost all visits, the timestamp of ahoy_visits.started_at isn't equal to the earliest ahoy_events.time.  In some cases, I've seen the ahoy_visit timestamp as much as 45 seconds after the first event - which seems somewhat counterintuitive.  I've also seen the reverse where the first event has a timestamp significantly before the visit.  This all seems counterintuitive to me since I would have expected the two timestamps to be equal.

Is this type of thing expected?

```
SELECT
  ahoy_visits.visit_token,
  MIN(ahoy_events.time) as min_events_timestamp,
  MIN(ahoy_visits.started_at) as min_visit_timestamp,
  MIN(ahoy_events.time) - MIN(ahoy_visits.started_at) as diff

FROM
  ahoy_visits

LEFT JOIN
  ahoy_events
ON
  ahoy_events.visit_id = ahoy_visits.id

WHERE
  ahoy_visits.started_at >= '2018-06-01'

GROUP BY
  ahoy_visits.visit_token



             visit_token              |    min_events_timestamp    |    min_visit_timestamp     |       diff
--------------------------------------+----------------------------+----------------------------+------------------
 3147df8e-3d4b-4d00-a6d2-f28b0675effe | 2018-06-25 18:33:59.976999 | 2018-06-25 18:34:02.408298 | -00:00:02.431299
 1a99fc0f-a547-426f-a099-4d1a8e2aa776 | 2018-06-04 06:51:10.760681 | 2018-06-04 06:51:02.474065 | 00:00:08.286616
 eb0b0386-909a-40b3-ab87-4e604ef13328 | 2018-07-06 02:35:40.046999 | 2018-07-06 02:35:40.767822 | -00:00:00.720823
```

**Comment by ankane** [comment]
Hey @josh-m-sharpe, a few explanations come to mind:

1. Visits can start without any events (in both Ruby and JavaScript). This could explain cases where the visit starts early.
2. Even when a visit is created due to an event, the visit will be created slightly before.
3. If you use JavaScript, the time associated with an events comes from the client. The server ensures it is within a minute of the server time (or discards it and uses the server time). This could explain differences in either direction.
4. If you have multiple servers, the clocks may not be synchronized.

Ahoy may be able to do something about 2 and 3.

**Comment by ankane** [comment]
Visits contain useful info even if you decide not to track individual events.

The commit above should fix 2, 3, and 4. Think we can close this out.
