### ISSUE TITLE
Disabling Ahoy in the initializer

### ISSUE THREAD

**Issue by abinoda** [ankane/ahoy#383]
Thanks for creating and maintaining this awesome library! I am wondering if there is a simple way to disable Ahoy in the initializer?

The use case is that I use Ahoy in the [hosted version of my app](https://github.com/marketplace/pull-reminders/), but I want to disable it in the on-premises/self-hosted version of my app with an environment variable flag. I could see this being helpful in general in multi-environment workflows.

As an example, Rollbar has a `enabled` config option:
```ruby
Rollbar.configure do |config|
  config.enabled = false
end
```

**Comment by ankane** [comment]
Hey @abinoda, the closest thing Ahoy has is `exclude_method`, where you can do:

```ruby
Ahoy.exclude_method = lambda do |controller, request|
  !ENV["SELF_HOSTED"]
end
```

https://github.com/ankane/ahoy#exclusions

**Comment by ndbroadbent** [comment]
Haha wow, I had exactly the same question. I just set up `ahoy` recently, and now I'm also trying to disable it for my on-site version.

It looks like `Ahoy.exclude_method` will work, but I think it would also be nice if we could just set `Ahoy.enabled = false` in `config/initializers/ahoy.rb`. Because I also have some calls to `ahoy.track` that I'd like to disable.

**Comment by abinoda** [comment]
@ankane Thanks a lot! That should do the trick.

**Comment by abinoda** [comment]
I added this one-liner:
```ruby
Ahoy.exclude_method = -> (controller, request) { ENV['ON_PREMISES'] }
```
