### ISSUE TITLE
ahoy + Geocoder

### ISSUE THREAD

**Issue by irobayna** [ankane/ahoy#4]
Looking at the sourcecode `ahoy / lib / ahoy / model.rb` I see a method called `set_location` which appears calls GeoCoder directly.

Is there anything special I have to do besides include the Geocode gem in my project to use geocoding by ip ?

I have added latitude/longitude fields to the visit model but not sure these fields are needed.

Any help would be greately appreciated!

**Comment by Martin-Fritsche** [comment]
I'm trying to use this gem, but the location part is not getting updated in the database.  I basically followed the instructions: included gem 'ahoy_matey' in Gemfile

ran 
bundle install
rails generate ahoy:install
rails db:migrate

included gem 'geocoder' in Gemfile

included in config/initializers/ahoy.rb
Ahoy.api = true (Because I am use react on the frontend)
Ahoy.geocode = true 

Still, when I look in the database at the ahoy_visits table, all entries have country, region, city, longitude and latitude set to nil.

I am running the app in production mode on heroku and in staging mode on digital ocean.  On both platforms and in both modes, I still get the nil values.

What I'm I doing wrong
