### ISSUE TITLE
Ahoy::Event user_id field always nil (but user_id in Ahoy::Visit set correctly)

### ISSUE THREAD

**Issue by jfanals** [ankane/ahoy#401]
Out of the box Ahoy is adding correctly the `user_id` to `Ahoy::Visit` (without having to configure the `Ahoy.user_method`)

The `Ahoy::Event` is correctly linked to the `Ahoy::Visit` via `visit_id`, but the `user_id` in `Ahoy::Event` is always set to `nil`.

I looked at `Ahoy.js` library and tried

    ahoy.configure({withCredentials: true});

But this did not manage to set the `user_id` on `Ahoy::Event` (it is still `nil`)

I can get to an `Ahoy::Event` user info by first querying its linked `Ahoy::Visit`, witch makes sense as `Ahoy::Visit` gets updated after the user logs in.

What is the use of the `user_id` field in `Ahoy::Event`? How to correctly set it up?

**Comment by ankane** [comment]
Hey @jfanals, the `user_id` field on events indicates if the user was logged in when the server received the event.

It seems like your authentication credentials are not being passed to the backend with events. See [this link](https://github.com/ankane/ahoy.js#users) for more details. The `withCredentials` and `headers` options are only available on Ahoy master, so that may be the issue.

**Comment by jfanals** [comment]
Hi @ankane, thank you for your quick response.

I am not sure what you mean by "only available on Ahoy master".

Does it mean that I have to use the master branch of `ankane/ahoy` in order for it to work (instead of v 2.2.0)?

**Comment by ankane** [comment]
Yeah, that's what it means.

**Comment by jfanals** [comment]
Thank you!

BTW. I love your gems, your creations are making a great impact on the projects I am working on.
