### ISSUE TITLE
UTM fields not updating on production 

### ISSUE THREAD

**Issue by fmuneer-c** [ankane/ahoy#503]
Hi,

The utm fields are not updating on production. Could anybody let me know what is the issue? They are working if Ahoy.cookies is FALSE otherwise it is creating cookies only when user signed in but when user goes to any other page it is not creating / updating with utm fields.

**Comment by joshmrallen** [comment]
Hi there,

I collaborate with @fmuneer-c and here's some extra info:
---

## Versions & Environment:
- hosted on heroku
- ahoy_matey gem version: 3.2.0
- Rails 6.1 -- updated recently, but problem started happening when we were still on Rails.5.2.6
- so since we were on 5.2.6, the drop of support for < Rails 5.2 update on ahoy_matey version 4.0.0 doesn't really apply
- Ruby 2.6.6

## Initialzer:
```
# config/initializers/ahoy.rb:

Ahoy.api = true
Ahoy.server_side_visits = false
Ahoy.user_agent_parser = :legacy
Ahoy.geocode = false


class Ahoy::Store < Ahoy::DatabaseStore
  def track_visit(data)
    data[:id] = ensure_uuid(data.delete(:visit_token))
    data[:visitor_id] = ensure_uuid(data.delete(:visitor_token))
    super(data)
  end

  def track_event(data)
    data[:id] = ensure_uuid(data.delete(:event_id))
    super(data)
  end

  def visit
    @visit ||= visit_model.find_by(id: ensure_uuid(ahoy.visit_token)) if ahoy.visit_token
  end

  def visit_model
    Visit
  end

  UUID_NAMESPACE = UUIDTools::UUID.parse("a82ae811-5011-45ab-a728-569df7499c5f")

  def ensure_uuid(id)
    UUIDTools::UUID.parse(id).to_s
  rescue
    UUIDTools::UUID.sha1_create(UUID_NAMESPACE, id).to_s
  end
end
```

## User model:
```
# app/models/user.rb
class User < ApplicationRecord
     visitable class_name: "Visit"

    has_many :visits

     ...
end
```

## Visit model:
```
# app/models/visit.rb

class Visit < ApplicationRecord
     self.primary_key = :id
     has_many :ahoy_events, class_name: "Ahoy::Event"
     belongs_to :user

end
```

## More info:
- Original install created ahoy::visit model, which past devs changed to the Visit table and removed from the `ahoy` namespace

## Attempts:
- Upgrading to latest version didn't work
- Tried changing config for server_side_visits
- Tried setting Ahoy.cookies = false, but this results in an instance being created for every page a user visits which isn't preferable for our app due to database load and bloat. We only really need Ahoy for generating first-party analytics

## Issues/Articles referenced:
- https://github.com/ankane/ahoy/issues/289
- - this issue doesn't have a solution noted 
- https://stackoverflow.com/questions/61350966/rails-ahoy-new-visits-not-being-created
- - this article was helpful for the initializer example, but wasn't relevant to our situation

## More context:
- utm fields in the Visit instance were updating as expected all the way up to the end of november
- We noticed that all Visit instances starting December 1st contained `nil` for all utm fields -- which was strange because it's a heavily used feature by our users
- the only change at the end of November / beginning of December was adding an 's' to 'http' to make 'https' in `config/environemnts/production.rb` to the following line:
```
config.action_mailer.default_url_options = { :host => "http://www.ourdomain.com"  }
```

**Comment by ankane** [comment]
Hey @fmuneer-c and @joshmrallen, I'd recommend forking and adding debugging to see what's going on. If you're using the JavaScript library, a good place to start would be see if UTM parameters are being passed to the `/ahoy/visits` endpoint.
