### ISSUE TITLE
Unique Violation events primary key

### ISSUE THREAD

**Issue by dylanjha** [ankane/ahoy#66]
I'm seeing these errors pop up. Am I misusing this library somehow?

PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "ahoy_events_pkey"
DETAIL: Key (id)=(8731dd56-0a9f-4722-9229-4a843c144b68) already exists.

I initialize ahoy javascript like this:
```javascript
$(document).ready(ahoy.trackAll)
```

The only custom code I have is that in the action when users sign up I call this:

```ruby
 ahoy.track "Signed Up"
```

I'm using turbolinks if that has anything to do with it.

**Comment by ankane** [comment]
Ahoy will attempt to send visit events until it receives a success response from the server.  This can result in a single event being sent multiple times.  To account for this, Ahoy will try to insert the event, but the unique constraint will prevent it.  This is by design.  It looks like Ahoy just needed to rescue the additional error type.

**Comment by dylanjha** [comment]
thanks @ankane
