### ISSUE TITLE
Reoccurring schema.rb changes when collaborating

### ISSUE THREAD

**Issue by codeanpeace** [ankane/ahoy#72]
The - and + lines reflect changes that happen to the schema.rb file when one person on the team pushes to master and are reversed when another person on the team pushes. Any idea why this might be happening - the reoccurring change is basically the inclusion and removal of `default: "uuid_generate_v4()"`

```
  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"
  enable_extension "uuid-ossp"

-  create_table "ahoy_events", id: :uuid, default: "uuid_generate_v4()", force: true do |t|
+  create_table "ahoy_events", id: :uuid, force: true do |t|

-  create_table "visits", id: :uuid, default: "uuid_generate_v4()", force: true do |t|
+  create_table "visits", id: :uuid, force: true do |t|
```

**Comment by mchristen** [comment]
I've noticed this happening as well.

It seems to happen sometimes after I do a rake db:rollback followed by a rake db:migrate. The only thing I can think of about the migration I'm rolling back and running again when I first noticed the problem is that it is adding fields to a table that has a foreign_key for visit_id.

**Comment by ankane** [comment]
Cleaning up issues.
