### ISSUE TITLE
Track Time spent on view?

### ISSUE THREAD

**Issue by ngelx** [ankane/ahoy#87]
Hi, there is any way to track spent time on a view?

**Comment by ankane** [comment]
Hey @ngelx, you can pass the time spent as a property.  To get the time spent, you'd have to reference the Rails docs.

**Comment by ngelx** [comment]
Hey @ankane, thanks for your answer. Let me reformulate the question, it was poorly addressed. 

I'm doing something like 

```
window.onbeforeunload = function (event) {
    ahoy.track("ActivityTime", {time: xx});
}
```

But since ahoy.track is doing async request, it isn't working. So the questions are: 

1- There is any way to do sync request? 
2- More over, there is any specific function (like trackClicks, trackView or similar) that implement this? 

Thanks in advance

**Comment by ankane** [comment]
@ngelx Ah, I see.  By design, Ahoy doesn't try the async request right away.  Instead, it sets a cookie and waits a second. If the user navigates, Ahoy sends the event on the next page you visit.  Of course, this approach doesn't work with external URLs.  There's currently no mechanism for delaying navigation until the event is tracked.
